config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :rubros
  resources :categoris

  resources :negocios do
		resources :productos
	 end

	root 'negocios#index'
	
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	# miservidor.com/
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/categori.rb
class Categori < ApplicationRecord
	has_many :productos
end

app/models/negocio.rb
class Negocio < ApplicationRecord
	belongs_to :user
	has_many :productos
	before_save :first_estatus

	#has_attached_file :imagen, styles: { medium: "1280x720" , thumb: "800x600" }
	#has_attached_file :imagen

	#validates_attachment_content_type :imagen, :content_type => /\Aimage/
	#validates_attachment_content_type :imagen, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


    has_attached_file :imagen, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/
  
  def first_estatus
     self.estatus = true if estatus.blank?
     
  end

end

app/models/producto.rb
class Producto < ApplicationRecord
  belongs_to :categori
  belongs_to :negocio
end

app/models/rubro.rb
class Rubro < ApplicationRecord
	#has_many :negocio
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :negocios
end

app/controllers/api/kindles_controller.rb
class Api::KindlesController < ApplicationController
	respond_to :json
	PER_PAGE_RECORDS = 9

	def index
		kindles_paginated = Kindle.order('id').page(params[:page]).per(PER_PAGE_RECORDS)
		json_response = {
			
			models: kindles_paginated,
			current_page: params[:page].to_i,
			perPage: PER_PAGE_RECORDS

		}

		respond_with json_response, callback: params[:callback]
	end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/categoris_controller.rb
class CategorisController < ApplicationController
  before_action :set_categori, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categoris = Categori.all
    respond_with(@categoris)
  end

  def show
    respond_with(@categori)
  end

  def new
    @categori = Categori.new
    respond_with(@categori)
  end

  def edit
  end

  def create
    @categori = Categori.new(categori_params)
    @categori.save
    respond_with(@categori)
  end

  def update
    @categori.update(categori_params)
    respond_with(@categori)
  end

  def destroy
    @categori.destroy
    respond_with(@categori)
  end

  private
    def set_categori
      @categori = Categori.find(params[:id])
    end

    def categori_params
      params.require(:categori).permit(:nombre, :estatus)
    end
end

app/controllers/negocios_controller.rb
class NegociosController < ApplicationController
  before_action :set_negocio, only: [:show, :edit, :update,  :destroy]
  #before_action :validate_user, except: [:show , :index]
  before_action :authenticate_user!, except: [:show , :index]
  before_action :solo_creador, only: [:edit, :update,  :destroy]
  respond_to :html

  def index
    @negocios = Negocio.all
    respond_with(@negocios)
  end

  def show
    @productos = Producto.all

    @producto = Producto.new
  end

  def new
    @negocio = Negocio.new
    respond_with(@negocio)
  end

  def edit

  end

  def create
    @negocio = current_user.negocios.new(negocio_params)
    @negocio.save
    respond_with(@negocio)
  end

  def update
    @negocio.update(negocio_params)
    respond_with(@negocio)
  end

  def destroy
    @negocio.destroy
    respond_with(@negocio)
  end

  def solo_creador
    unless @negocio.user_id == current_user.id

      redirect_to negocios_path, notice: "Solo el creador del negocio puede realizar esta acción"
      
    end
  end


  private

    def set_negocio
      @negocio = Negocio.find(params[:id])
    end

    def negocio_params
      params.require(:negocio).permit(:nombre, :estatus, :correo, :user_id , :tipo_documento_legal, :documento_legal, :direccion , :imagen)
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]
  before_action :set_negocio

  respond_to :html



  def show
    respond_with(@negocio,@producto)
  end

  def new
    @producto = Producto.new
    respond_with(@negocio,@producto)
  end

  def edit
  end

  def create
    @producto = Producto.new(producto_params)
    @producto.negocio = @negocio
    @producto.save
       respond_with(@negocio,@producto)

  end

  def update
    @producto.update(producto_params)
    respond_with(@producto)
  end

  def destroy
    @producto.destroy
    respond_with(@negocio,@producto)
  end

  private


    def set_negocio
      @negocio = Negocio.find(params[:negocio_id])      
    end

    def set_producto
      @producto = Producto.find(params[:id])
    end

    def producto_params
      params.require(:producto).permit(:nombre, :estatus, :categori_id, :negocio_id , :precio_dolar)
    end
end

app/controllers/rubros_controller.rb
class RubrosController < ApplicationController
  before_action :set_rubro, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @rubros = Rubro.all
    respond_with(@rubros)
  end

  def show
    respond_with(@rubro)
  end

  def new
    @rubro = Rubro.new
    respond_with(@rubro)
  end

  def edit
  end

  def create
    @rubro = Rubro.new(rubro_params)
    @rubro.save
    respond_with(@rubro)
  end

  def update
    @rubro.update(rubro_params)
    respond_with(@rubro)
  end

  def destroy
    @rubro.destroy
    respond_with(@rubro)
  end

  private
    def set_rubro
      @rubro = Rubro.find(params[:id])
    end

    def rubro_params
      params.require(:rubro).permit(:nombre, :estatus)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/categoris_helper.rb
module CategorisHelper
end

app/helpers/negocios_helper.rb
module NegociosHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/rubros_helper.rb
module RubrosHelper
end

app/views/categoris/_form.html.erb
<div class="text-center">
  <%= form_with(model: categori, local: true) do |form| %>
    <% if categori.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(categori.errors.count, "error") %> prohibited this categori from being saved:</h2>
        <ul>
          <% categori.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>

      <div class="field">
        <%= form.label :nombre %>
        <%= form.text_field :nombre %>
      </div>

      <div class="field">
        <%= form.label :estatus %>
        <%= form.check_box :estatus %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/categoris/edit.html.erb
<h1>Editing Categori</h1>

<%= render 'form', categori: @categori %>

<%= link_to 'Show', @categori %> |
<%= link_to 'Back', categoris_path %>

app/views/categoris/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categoris</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoris.each do |categori| %>
      <tr>
        <td><%= categori.nombre %></td>
        <td><%= categori.estatus %></td>
        <td><%= link_to 'Show', categori %></td>
        <td><%= link_to 'Edit', edit_categori_path(categori) %></td>
        <td><%= link_to 'Destroy', categori, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categori', new_categori_path %>

app/views/categoris/new.html.erb
<h1>New Categori</h1>

<%= render 'form', categori: @categori %>

<%= link_to 'Back', categoris_path %>

app/views/categoris/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<strong>Nombre:</strong>
	<%= @categori.nombre %>
</p>

<p>
	<strong>Estatus:</strong>
	<%= @categori.estatus %>
</p>

<%= link_to 'Edit', edit_categori_path(@categori) %> |
<%= link_to 'Back', categoris_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Global Business</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<header class="container-fluid bg-dark text-white h-20">
		<nav class="navbar navbar-expand-lg">

			<div class='navbar-brand'>
				<%= image_tag("logo4.png", size: "150x150", :alt => "logo") -%>
			</div>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<%= link_to "Negocios", negocios_path, class: 'btn btn-outline-secondary btn-sm text-decoration-none' %>
					</li>
					<% unless user_signed_in? %>
					<li class="nav-item">
						<%= link_to "Iniciar Sesión", user_session_path, class: 'btn btn-outline-secondary btn-sm text-decoration-none' %>
					</li>
					<li class="nav-item">
						<%= link_to "Registrarme", new_user_registration_path, class: 'btn btn-outline-secondary btn-sm text-decoration-none' %>
					</li>
					<%end %>
					<% if user_signed_in? %>
					<li class="nav-item">
						<%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary btn-sm text-decoration-none' %>
					</li>
					<%end %>
				</ul>
				<form class="form-inline my-2 my-lg-0">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
			</div>
		</nav>
	</header>

	<section class="container">
		<%= yield %>
	</section>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
</body>

</html>

app/views/negocios/_form.html.erb
<div class="text-center">
      <%= form_with(model: negocio, remote: true) do |form| %>
        <% if negocio.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(negocio.errors.count, "error") %> prohibited this negocio from being saved:</h2>

            <ul>
              <% negocio.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :nombre %>
          <%= form.text_field :nombre %>
        </div>


        <div class="field">
          <%= form.label :correo %>
          <%= form.text_field :correo %>
        </div>


        <div class="field">
          <%= form.label :direccion %>
          <%= form.text_field :direccion %>
        </div>

        <div class="field">
          <%= form.label :documento_legal %>
          <%= form.number_field :documento_legal %>
        </div>

        <div class="field">
          <%= form.label :tipo_documento_legal %>
          <%= form.select( :tipo_documento_legal, ["V" , "J"] , {include_blank: 'Seleccione'})  %>
        </div>

        <div class="field">
          IMAGEN DE TU NEGOCIO <%= form.file_field :imagen %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
</div>

app/views/negocios/edit.html.erb
<h1>Editando Negocio</h1>

<%= render 'form', negocio: @negocio %>

<%= link_to 'Show', @negocio %> |
<%= link_to 'Back', negocios_path %>

app/views/negocios/index.html.erb
      <div class="jumbotron p-3 p-md-5 text-black rounded fondo2">

        <div class="col-md-6 px-2">

        <% if user_signed_in? %>
              <h2> Hola <%= current_user.email %></h2>
        <%end%>

          <h1 class="display-4 font-italic">Bienvenido a Global Busines.</h1>

          <p class="lead my-3">Donde podras encontrar los negocios segun la ubicacion que desees, y ver sus productos como si estuvieras en la propia tienda.</p>
       
        </div>


      </div>




      <div class="row mb-2">

                   <% @negocios.each do |negocio| %>  
              <div class="col-md-6 px-2">
               
                          <div class="card flex-md-row mb-4 shadow-sm style">

                                <div class="card-body d-flex flex-column align-items-start">

                                      <h3 class="mb-0"><%= negocio.nombre %></h3>
                                        
                                      

                                      <div class="mb-1">

                                        <td><%= negocio.direccion %></td>
                                        <br> 
                                        <td><%= negocio.correo %></td>
                                        
                                      </div>    
                                      <div >

                                        <td><%= link_to 'Edit', edit_negocio_path(negocio) %></td>
                                        <td><%= link_to 'Destroy', negocio, method: :delete, data: { confirm: 'Are you sure?' } %></td>

                                      </div>    

                                      <a class="btn" href="#"><%= link_to 'Visitar Negocio', negocio %></a>
                                </div>

                                <div ><%= image_tag( negocio.imagen.url(), size: "50x50", :alt => "logo" ) -%></div>

                          </div>

              </div>
                   <% end %>
                    
      </div>
<div class="text-center">
  <h1><%= link_to '!Ingresa ya mismo tu Negocio con nosotros!', new_negocio_path %></h1>
</div>

app/views/negocios/new.html.erb
<h1 class="text-center">Nuevo Negocio</h1>

<%= render 'form', negocio: @negocio %>

<%= link_to 'Back', negocios_path %>

app/views/negocios/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-6 px-0"> 
      <h1 class="display-4 font-italic"> <%= @negocio.nombre %> </h1>
      <p class="lead my-3"> Información: </p> <br>
      <p class="lead mb-0">Correo Electronico: <%= @negocio.correo %></p><br>
      <p class="lead mb-0">Dirección: <%= @negocio.direccion %></p>
    </div>
    <br>
    <br>
<div>

  <h1>Negocio elaborado por <%= @negocio.user.email%></h1>

</div>

<h1>Productos</h1>

 <div class="row mb-2">
                   <% @negocio.productos.each do |producto| %>  
              <div class="col-md-6">
               
                          <div class="card flex-md-row mb-4 shadow-sm h-md-250">

                                <div class="card-body d-flex flex-column align-items-start">

                                  <h3 class="mb-0">
                                    <a class="text-dark" href="#"><%= producto.nombre %> </a>
                                  </h3>

                                  <div class="mb-1 text-muted"><%= producto.nombre %></div>
                                 <%if producto.estatus %>    
                                  <div class="green">DISPONIBLE</div> 
                                 <%else %>  
                                  <div class="red">NO DISPONIBLE</div>
                                 <%end%> 

                                  <div >PRECIO: <%= producto.precio_dolar %> $</div>    
                                  <% if user_signed_in? %>
                                  <div >              
                                    <td><%= link_to 'Editar',  edit_negocio_producto_path(@negocio,producto) %></td>
                                    <td><%= link_to 'Destruir', negocio_producto_path(@negocio,producto), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                  </div>    
                                  <%end%>

                                </div>
                                <h1 class="card-img-right flex-auto d-none d-lg-block" style="width: 300px; height: 250px;margin: 5px;"><%= image_tag( "oreo.jpg", size: "250x250", :alt => "logo") -%></h1>

                          </div>

              </div>
                   <% end %>

  </div>




<div class="field">

  <h3>Productos</h3>
  <%= render "productos/form" %>
  
</div>

<%= link_to 'Edit', edit_negocio_path(@negocio) %> |
<%= link_to 'Back', negocios_path %>

app/views/productos/_form.html.erb
   <div class="text-center">  

      <%= form_for([@negocio,@producto]) do |form| %>
        <% if @producto.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

            <ul>
              <% @producto.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :nombre %>
          <%= form.text_field :nombre %>
        </div>

        <div class="field">
          <%= form.label :estatus %>
          <%= form.check_box :estatus %>
        </div>

        <div class="field">
              <%= form.label :categori_id, "Categoria del Producto" %>
              <%= form.select("categori_id", Categori.all.collect {|p| [p.nombre , p.id] }, {include_blank: 'Seleccione'}) %>
        </div>


        <div class="field">
          <%= form.label :precio_dolar %>
          <%= form.text_field :precio_dolar %>


        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
      
</div>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form'%>

<%= link_to 'Show', negocio_producto_path(@negocio,@producto) %> |
<%= link_to 'Back', negocio_productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>


 <h1>Productos</h1>

 <div class="row mb-0">
                   <% @negocio.productos.each do |producto| %>  
              <div class="col-md-4">
               
                          <div class="card flex-md-row mb-4 shadow-sm h-md-250">

                                <div class="card-body d-flex flex-column align-items-start">

                                  <h3 class="mb-0">
                                    <a class="text-dark" href="#"><%= producto.nombre %> </a>
                                  </h3>

                                  <div class="mb-1 text-muted"><%= producto.nombre %></div>
                                 <%if producto.estatus %>    
                                  <div class="green">DISPONIBLE</div> 
                                 <%else %>  
                                  <div class="red">NO DISPONIBLE</div>
                                 <%end%> 

                                  <div >PRECIO: <%= producto.precio_dolar %> $</div>    
                                  <% if user_signed_in? %>
                                  <div >              
                                    <td><%= link_to 'Editar', edit_negocio_producto_path(@negocio,producto) %></td>
                                    <td><%= link_to 'Destruir', negocio_producto_path(@negocio,producto), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                  </div>    
                                  <%end%>

                                </div>
                                <h1 class="card-img-right flex-auto d-none d-lg-block" style="width: 300px; height: 250px;margin: 5px;"><%= image_tag( "oreo.jpg", size: "250x250", :alt => "logo") -%></h1>

                          </div>

              </div>
                   <% end %>

  </div>
<%= link_to 'New Producto', new_negocio_producto_path %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', negocio_productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Nombre:</strong>
  <%= @producto.nombre %>
</h1>

<h1>
  <strong>Estatus:</strong>
  <%= @producto.estatus %>
</h1>

<h1>
  <strong>Categoria:</strong>
  <%= @producto.categori_id %>
</h1>

<h1>
  <strong>Precio dolar:</strong>
  <%= @producto.precio_dolar %>
</h1>



<%= link_to 'Edit', edit_negocio_producto_path(@producto) %> |
<%= link_to 'Back', negocio_path(@negocio) %>

app/views/rubros/_form.html.erb
<%= form_with(model: rubro, local: true) do |form| %>
  <% if rubro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rubro.errors.count, "error") %> prohibited this rubro from being saved:</h2>

      <ul>
        <% rubro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :estatus %>
    <%= form.check_box :estatus %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rubros/edit.html.erb
<h1>Editing Rubro</h1>

<%= render 'form', rubro: @rubro %>

<%= link_to 'Show', @rubro %> |
<%= link_to 'Back', rubros_path %>

app/views/rubros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rubros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rubros.each do |rubro| %>
      <tr>
        <td><%= rubro.nombre %></td>
        <td><%= rubro.estatus %></td>
        <td><%= link_to 'Show', rubro %></td>
        <td><%= link_to 'Edit', edit_rubro_path(rubro) %></td>
        <td><%= link_to 'Destroy', rubro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rubro', new_rubro_path %>

app/views/rubros/new.html.erb
<h1>New Rubro</h1>

<%= render 'form', rubro: @rubro %>

<%= link_to 'Back', rubros_path %>

app/views/rubros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @rubro.nombre %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @rubro.estatus %>
</p>

<%= link_to 'Edit', edit_rubro_path(@rubro) %> |
<%= link_to 'Back', rubros_path %>